on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
  test_job:
    runs-on: ubuntu-latest
    name: Create tags
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag Semver
        uses: ./
        id: semver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}